import React, { useState } from 'react';
import { CheckCircle2, Clock, HeartHandshake, Mail, MapPin, Phone, Users } from 'lucide-react';

const emptyForm = { fullName: '', specialty: '', phone: '', city: '', availability: '' };

export default function Volunteer() {
  const [form, setForm] = useState(emptyForm);
  const [submitted, setSubmitted] = useState(false);
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = (event) => {
    event.preventDefault();
    const records = JSON.parse(localStorage.getItem('sfax-volunteer-applications') || '[]');
    localStorage.setItem('sfax-volunteer-applications', JSON.stringify([...records, { ...form, createdAt: new Date().toISOString() }]));
    setSubmitted(true);
  };

  return <>
    <section className="relative -mt-20 overflow-hidden px-4 pb-20 pt-40"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1560220604-1985ebfe28b1?w=1400&q=80&auto=format&fit=crop" alt="متطوعون يعملون معاً" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-primary/85" /></div><div className="relative z-10 mx-auto max-w-3xl text-center text-white"><span className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-secondary/20 text-secondary"><Users className="h-8 w-8" /></span><h1 className="font-heading text-4xl font-bold leading-snug lg:text-5xl">انضمّ إلى عائلة المتطوّعين</h1><p className="mt-5 text-lg leading-loose text-secondary/90">وقتك وخبرتك عطاءٌ لا يُقدّر بثمن. سجّل اهتمامك وسيتواصل فريق الجمعية معك.</p></div></section>
    <section className="px-4 py-20"><div className="mx-auto grid max-w-5xl gap-10 lg:grid-cols-[1fr_1.3fr] lg:items-start"><aside className="rounded-3xl bg-primary p-8 text-white shadow-card"><HeartHandshake className="h-10 w-10 text-secondary" /><h2 className="mt-5 font-heading text-2xl font-bold">أين يمكن أن تساهم؟</h2><ul className="mt-6 space-y-5 text-secondary/90"><li className="flex gap-3"><Users className="mt-1 h-5 w-5 shrink-0 text-secondary" />تنظيم الحملات والفعاليات الميدانية</li><li className="flex gap-3"><Clock className="mt-1 h-5 w-5 shrink-0 text-secondary" />مساعدة مرنة وفق أوقات توفّرك</li><li className="flex gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-secondary" />فرص قريبة من مدينتك وحيّك</li></ul><p className="mt-8 border-t border-white/15 pt-6 text-sm leading-loose text-white/70">هذه النسخة من الموقع تحفظ الطلب على جهازك فقط. ليتواصل معك الفريق فعلياً، أرسل بياناتك أيضاً إلى البريد الرسمي أدناه.</p><a href="mailto:contact@khairia-sfax.org?subject=طلب%20تطوع" className="mt-4 inline-flex items-center gap-2 font-bold text-secondary hover:text-white"><Mail className="h-4 w-4" />contact@khairia-sfax.org</a></aside>
      <div className="rounded-3xl border border-border bg-card p-8 shadow-card sm:p-10">{submitted ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-green-600" /><h2 className="mt-5 font-heading text-2xl font-bold text-primary">شكراً لاهتمامك بالتطوّع</h2><p className="mx-auto mt-3 max-w-md leading-loose text-muted-foreground">حُفظ طلبك على هذا الجهاز. لضمان وصوله إلى فريق الجمعية، أرسله إلى البريد الإلكتروني الظاهر في الصفحة.</p><button type="button" onClick={() => { setForm(emptyForm); setSubmitted(false); }} className="mt-7 rounded-full bg-primary px-6 py-3 font-bold text-white hover:bg-primary-hover">تقديم طلب آخر</button></div> : <form onSubmit={submit} className="space-y-5"><div><h2 className="font-heading text-2xl font-bold text-primary">نموذج الاهتمام بالتطوّع</h2><p className="mt-2 text-muted-foreground">الحقول المعلّمة مطلوبة.</p></div><Field label="الاسم الكامل" name="fullName" value={form.fullName} onChange={update} required autoComplete="name" /><Field label="التخصص أو المهارة" name="specialty" value={form.specialty} onChange={update} required placeholder="مثال: تعليم، طب، لوجستيك، إعلام" /><Field label="رقم الهاتف" name="phone" value={form.phone} onChange={update} required type="tel" inputMode="tel" autoComplete="tel" dir="ltr" placeholder="+216 ..." /><Field label="المدينة أو الولاية" name="city" value={form.city} onChange={update} required autoComplete="address-level2" /><label className="block font-heading text-sm font-bold text-primary">أوقات التوفّر <span className="text-accent">*</span><textarea name="availability" value={form.availability} onChange={update} required rows="4" placeholder="الأيام أو الساعات التي تناسبك" className="mt-2 w-full resize-y rounded-xl border border-input bg-background px-4 py-3 text-primary focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20" /></label><button type="submit" className="flex w-full items-center justify-center gap-2 rounded-full bg-accent px-8 py-4 font-heading font-bold text-white shadow-lg transition hover:bg-accent-hover"><HeartHandshake className="h-5 w-5" />حفظ طلب التطوّع</button><p className="text-center text-xs text-muted-foreground">لا يُرسل هذا النموذج تلقائياً إلى خادم في النسخة الحالية.</p></form>}</div></div></section>
    <section className="bg-secondary/10 px-4 py-16"><div className="mx-auto max-w-4xl text-center"><h2 className="font-heading text-3xl font-bold text-primary">تواصل مباشرةً</h2><p className="mt-3 text-muted-foreground">يمكنك التواصل مع الجمعية قبل أو بعد تسجيل اهتمامك.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><a href="tel:+21674000000" className="flex items-center justify-center gap-3 rounded-2xl border border-border bg-card p-5 font-bold text-primary transition hover:border-accent"><Phone className="h-5 w-5 text-accent" /><span dir="ltr">+216 74 000 000</span></a><a href="mailto:contact@khairia-sfax.org" className="flex items-center justify-center gap-3 rounded-2xl border border-border bg-card p-5 font-bold text-primary transition hover:border-accent"><Mail className="h-5 w-5 text-accent" />contact@khairia-sfax.org</a></div></div></section>
  </>;
}

function Field({ label, name, required, ...props }) { return <label className="block font-heading text-sm font-bold text-primary">{label} {required && <span className="text-accent">*</span>}<input name={name} required={required} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-primary focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20" {...props} /></label>; }
